### ISSUE TITLE
Cannot access configuration in docker

### ISSUE THREAD

**Issue by ztytotoro** [aspnet/AspNetCore#10363]
### Describe the bug
The program can't access configuration inside a docker container

### To Reproduce
1. Using this version of ASP.NET Core '2.2'
2. Write some code to read the configuration in appSettings.json
3. Publish the source code to a folder
4. Run it with docker compose file
```yaml
version: "3.7"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
    expose:
      - 5432

  service:
    image: mcr.microsoft.com/dotnet/core/aspnet:2.2-stretch-slim
    restart: always
    volumes:
      - ./app:/home/ubuntu/homework/service/app
    entrypoint:
      - dotnet
      - /home/ubuntu/homework/service/app/Service.dll
    ports:
      - 4201:80
    depends_on:
      - db
    links:
      - db
```

### Expected behavior
The code works fine without docker

### Additional context
If I change the code in `Startup.cs`, It works fine.
```cs
        public Startup(IHostingEnvironment env)
        {
            Configuration = new ConfigurationBuilder()
              .AddJsonFile("appsettings.json")
              //.AddJsonFile($"appsettings.{env.EnvironmentName}.json") This line will cause an file not exist error even file exists
              .AddEnvironmentVariables()
              .Build();
        }

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddSingleton(Configuration);
        }
```
