### ISSUE TITLE
SignalR not working properly on Ubuntu

### ISSUE THREAD

**Issue by michasacuer** [aspnet/AspNetCore#17284]
### Describe the bug
SignalR not work properly with `Github Actions` and Ubuntu machine

### To Reproduce

After setting up my workflow on `Github Actions` with this yaml and Ubuntu machine:

``` yaml
name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Restoring and building every csproj here
       run: related comands for this
    - name: Run Functional Tests
      run: dotnet test Src/Tests/TaskManager.Tests.WebFunctional
```

My integration test with `SignalR` dont work correctly. Test looks like this:

``` C#
    public class TestConnection : IClassFixture<CustomWebApplicationFactory<TestStartup>>
    {
        private readonly HttpClient client;

        private readonly TestServer server;

        public TestConnection(CustomWebApplicationFactory<TestStartup> factory)
        {
            this.client = factory.CreateClient();
            this.server = factory.Server;
        }

        [Fact]
        public async Task CheckIfClientCanConnectToSignalRHub()
        {
            var hubConnection = new HubConnectionBuilder()
                .WithUrl("http://localhost/Notifications", o =>
                {
                    o.HttpMessageHandlerFactory = _ => this.server.CreateHandler();
                })
                .Build();

            await hubConnection.StartAsync();

            const string Message = "SignalR Works!";
            string response = string.Empty;

            hubConnection.On<string>("ReciveMessage", (message) => response = message);
            await hubConnection.InvokeAsync("SendMessage", Message);

            response.ShouldBe(Message);
        }
    }
```

After running it on my workflow, i get this output (you can check it [here](https://github.com/michasacuer/TaskManager/runs/312042912) too.

``` C#
[xUnit.net 00:00:04.37]     TaskManager.Tests.WebFunctional.ControllersTests.TestConnection.CheckIfClientCanConnectToSignalRHub [FAIL]
  X TaskManager.Tests.WebFunctional.ControllersTests.TestConnection.CheckIfClientCanConnectToSignalRHub [545ms]
  Error Message:
   Shouldly.ShouldAssertException : response
    should be
"SignalR Works!"
    but was
""
    difference
Difference     |  |    |    |    |    |    |    |    |    |    |    |    |    |    |   
               | \|/  \|/  \|/  \|/  \|/  \|/  \|/  \|/  \|/  \|/  \|/  \|/  \|/  \|/  
Index          | 0    1    2    3    4    5    6    7    8    9    10   11   12   13   
Expected Value | S    i    g    n    a    l    R    \s   W    o    r    k    s    !    
Actual Value   |                                                                       
Expected Code  | 83   105  103  110  97   108  82   32   87   111  114  107  115  33   
Actual Code    |                                                                       
  Stack Trace:
     at TaskManager.Tests.WebFunctional.ControllersTests.TestConnection.CheckIfClientCanConnectToSignalRHub() in /home/runner/work/TaskManager/TaskManager/Src/Tests/TaskManager.Tests.WebFunctional/ControllersTests/TestConnection.cs:line 48
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

So exception that was thrown was the exception from [`Shouldly`](https://github.com/shouldly/shouldly) not code itself (input not match with output).

Its intresting because on [CircleCi](https://circleci.com/gh/michasacuer/TaskManager/124?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) job everything works fine. How to inspect the problem with `github actions` that not showsin local `Test Explorer` and `CircleCi`? I bet its problem on `Ubuntu` where i run my workflow.

### Further technical details
- ASP.NET Core version: 3.0.1
